title:              Clean Blog
email:              qkfka9045@gmail.com
description:        KSB Open Source
author:             Start Bootstrap
baseurl:            "/blog"
url:                "https://kang-seongbeom.github.io/JekyllBlog/"

# Social Profiles
#twitter_username:   SBootstrap
github_username:    https://github.com/kang-seongbeom?tab=repositories
#facebook_username:  StartBootstrap
#instagram_username:  
#linkedin_username:

# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
